loader:
   build: dashboard
   command: node index.js
   links:
      - data
   environment:
      - ELASTICSEARCH_HOST=data
   volumes:
      - ./:/insee-elk-data
  

data:
    build: elastic
    environment:
       - ELASTICSEARCH_USER=dashboard
       - ELASTICSEARCH_PASS=dashboard
    volumes:
        - ./data:/data
        - ./config:/config
    ports:
       - "9200:9200"

kibana:
   image: kibana:4.1
   volumes:
       - ./config:/config
   ports:
      - "5601:5601"
   links:
      - data
   command: /opt/kibana/bin/kibana --config /config/kibana.yml